// ============================================
// i18n — Swahili / English Translation System
// ============================================

window.I18N = {
    lang: localStorage.getItem('pharmacy_lang') || 'en',
    translations: {
        en: {
            // Sidebar
            'Dashboard': 'Dashboard',
            'Medicines': 'Medicines',
            'Inventory': 'Inventory',
            'Sales': 'Sales',
            'Purchases': 'Purchases',
            'Suppliers': 'Suppliers',
            'Reports': 'Reports',
            'Profit & Loss': 'Profit & Loss',
            'Expenses': 'Expenses',
            'Expiry Monitor': 'Expiry Monitor',
            'Prescriptions': 'Prescriptions',
            'Users & Roles': 'Users & Roles',
            'Permissions': 'Permissions',
            'Activities': 'Activities',
            'Settings': 'Settings',
            'Backup & Restore': 'Backup & Restore',
            'Logout': 'Logout',
            // Page headers
            'Overview of your pharmacy operations': 'Overview of your pharmacy operations',
            'Manage your medicine inventory': 'Manage your medicine inventory',
            'Real-time stock tracking': 'Real-time stock tracking',
            'Manage sales transactions': 'Manage sales transactions',
            'Track purchase orders': 'Track purchase orders',
            'Manage supplier relationships': 'Manage supplier relationships',
            'Analytics and insights': 'Analytics and insights',
            'Revenue, costs and net profit': 'Revenue, costs and net profit',
            'Track operating expenses': 'Track operating expenses',
            'Monitor and manage expiring stock': 'Monitor and manage expiring stock',
            'Database backup management': 'Database backup management',
            'Process and dispense prescriptions': 'Process and dispense prescriptions',
            'Manage users and their roles': 'Manage users and their roles',
            'Manage module access per role': 'Manage module access per role',
            'View all system activities': 'View all system activities',
            'Configure system settings': 'Configure system settings',
            // Common
            'Loading...': 'Loading...',
            'No data found': 'No data found',
            'Failed to load': 'Failed to load',
            'Success': 'Success',
            'Error': 'Error',
            'Warning': 'Warning',
            'Cancel': 'Cancel',
            'Save': 'Save',
            'Delete': 'Delete',
            'Edit': 'Edit',
            'View': 'View',
            'Search': 'Search',
            'Filter': 'Filter',
            'Refresh': 'Refresh',
            'Print': 'Print',
            'Export': 'Export',
            'Close': 'Close',
            'Confirm': 'Confirm',
            'Yes': 'Yes',
            'No': 'No',
            'OK': 'OK',
            'Apply': 'Apply',
            'Generate': 'Generate',
            'Submit': 'Submit',
            'Processing...': 'Processing...',
            'Are you sure?': 'Are you sure?',
            // Sales
            'Sales Dashboard': 'Sales Dashboard',
            'Create Sale': 'Create Sale',
            'Period': 'Period',
            'Today': 'Today',
            'This Week': 'This Week',
            'This Month': 'This Month',
            'Last Month': 'Last Month',
            '3 Months': '3 Months',
            '5 Months': '5 Months',
            '6 Months': '6 Months',
            'This Year': 'This Year',
            '5 Years': '5 Years',
            'Custom Range': 'Custom Range',
            'Export CSV': 'Export CSV',
            'Transactions': 'Transactions',
            'Revenue': 'Revenue',
            'COGS': 'COGS',
            'Net Profit': 'Net Profit',
            'Avg Sale': 'Avg Sale',
            'Discounts': 'Discounts',
            'Gross Profit': 'Gross Profit',
            'Margin': 'Margin',
            'Generate Report': 'Generate Report',
            'Sales Records': 'Sales Records',
            'Invoice #': 'Invoice #',
            'Date': 'Date',
            'Customer': 'Customer',
            'Items': 'Items',
            'Subtotal': 'Subtotal',
            'Discount': 'Discount',
            'Total': 'Total',
            'Actions': 'Actions',
            'Create New Sale': 'Create New Sale',
            'Customer Name': 'Customer Name',
            'Sale Date': 'Sale Date',
            'Search Medicine': 'Search Medicine',
            'Quantity': 'Quantity',
            'Type medicine name to search...': 'Type medicine name to search...',
            'Sale Items': 'Sale Items',
            'Payment Method': 'Payment Method',
            'Cash': 'Cash',
            'Mobile Money': 'Mobile Money',
            'Bank Transfer': 'Bank Transfer',
            'Card': 'Card',
            'Credit': 'Credit',
            'Amount Paid': 'Amount Paid',
            'Change': 'Change',
            'Amount Due': 'Amount Due',
            'Notes': 'Notes',
            'Complete Sale': 'Complete Sale',
            // Purchases
            'New Purchase': 'New Purchase',
            'Supplier Name': 'Supplier Name',
            'Purchase Date': 'Purchase Date',
            'Purchase Items': 'Purchase Items',
            'Create Purchase': 'Create Purchase',
            'Batch No': 'Batch No',
            'Expiry Date': 'Expiry Date',
            'Buy Price': 'Buy Price',
            'Sell Price': 'Sell Price',
            'Add Item': 'Add Item',
            'Remove': 'Remove',
            // Medicines
            'Add Medicine': 'Add Medicine',
            'Medicine Name': 'Medicine Name',
            'Generic Name': 'Generic Name',
            'Brand': 'Brand',
            'Category': 'Category',
            'Form': 'Form',
            'Unit': 'Unit',
            'Strength': 'Strength',
            'Default Purchase Price': 'Default Purchase Price',
            'Default Selling Price': 'Default Selling Price',
            'Barcode': 'Barcode',
            'Save Medicine': 'Save Medicine',
            // Reports
            'Report Type': 'Report Type',
            'Purchases Report': 'Purchases Report',
            'Inventory Report': 'Inventory Report',
            'Expiry Report': 'Expiry Report',
            // P&L
            'Expenses': 'Expenses',
            'Profit Margin': 'Profit Margin',
            'Discounts Given': 'Discounts Given',
            'Monthly Revenue': 'Monthly Revenue',
            'Profit & Loss Trend': 'Profit & Loss Trend',
            // Users
            'Add User': 'Add User',
            'Full Name': 'Full Name',
            'Email': 'Email',
            'Password': 'Password',
            'Role': 'Role',
            'Staff': 'Staff',
            'Admin': 'Admin',
            'Active': 'Active',
            'Toggle Active': 'Toggle Active',
            // Suppliers
            'Add Supplier': 'Add Supplier',
            'Company Name': 'Company Name',
            'Contact Person': 'Contact Person',
            'Phone': 'Phone',
            'Address': 'Address',
            'Save Supplier': 'Save Supplier',
            // Login
            'Pharmacy Management': 'Pharmacy Management',
            'Secure access to your pharmacy dashboard': 'Secure access to your pharmacy dashboard',
            'Sign In': 'Sign In',
            'Notifications': 'Notifications',
            'Mark all read': 'Mark all read',
            // Branches
            'Branches': 'Branches',
            'Add Branch': 'Add Branch',
            'Branch Name': 'Branch Name',
            'Branch Code': 'Branch Code',
            'Location': 'Location',
            'Phone Number': 'Phone Number',
            'Save Branch': 'Save Branch',
            // Categories
            'Categories': 'Categories',
            'Add Category': 'Add Category',
            'Category Name': 'Category Name',
            'Description': 'Description',
            'Save Category': 'Save Category',
            // Manufacturers
            'Manufacturers': 'Manufacturers',
            'Add Manufacturer': 'Add Manufacturer',
            'Manufacturer Name': 'Manufacturer Name',
            'Country': 'Country',
            'Save Manufacturer': 'Save Manufacturer',
            // Customers
            'Customers': 'Customers',
            'Add Customer': 'Add Customer',
            'Customer Name': 'Customer Name',
            'Email': 'Email',
            'Save Customer': 'Save Customer',
            // Stock Adjustments
            'Stock Adjustments': 'Stock Adjustments',
            'New Adjustment': 'New Adjustment',
            'Adjustment Type': 'Adjustment Type',
            'Reason': 'Reason',
            'Adjust': 'Adjust',
            // Stock Transfers
            'Stock Transfers': 'Stock Transfers',
            'New Transfer': 'New Transfer',
            'From Branch': 'From Branch',
            'To Branch': 'To Branch',
            'Transfer Items': 'Transfer Items',
            'Transfer Stock': 'Transfer Stock',
            'In Transit': 'In Transit',
            'Received': 'Received',
            // Returns
            'Returns': 'Returns',
            'New Return': 'New Return',
            'Return Reason': 'Return Reason',
            'Process Return': 'Process Return',
            'Returned': 'Returned',
            'Pending': 'Pending',
            // Disposals
            'Disposals': 'Disposals',
            'New Disposal': 'New Disposal',
            'Disposal Reason': 'Disposal Reason',
            'Authority': 'Authority',
            'Dispose': 'Dispose',
            'Approved': 'Approved',
            'Disposed': 'Disposed',
            'TMDA Compliance': 'TMDA Compliance',
            // Upload Sales
            'Upload Sales': 'Upload Sales',
            'Upload Sales Document': 'Upload Sales Document',
            'Drag & drop your file here': 'Drag & drop your file here',
            'or click to browse': 'or click to browse',
            'Supported formats: CSV, Excel, PDF, DOCX, PNG, JPG': 'Supported formats: CSV, Excel, PDF, DOCX, PNG, JPG',
            'Choose File': 'Choose File',
            'Parse Document': 'Parse Document',
            'Confirm & Create Sales': 'Confirm & Create Sales',
            'Cancel': 'Cancel',
            'Back': 'Back',
            'Total Records': 'Total Records',
            'Valid Records': 'Valid Records',
            'Issues Found': 'Issues Found',
            'Found records in file': 'Found {count} sale record(s) in {file}. Review below and confirm to create sales.',
            'Has Issues': 'Has Issues',
            'Valid': 'Valid',
            'OK': 'OK',
            'Low Stock': 'Low Stock',
            'Out of Stock': 'Out of Stock',
            'Not Found': 'Not Found',
            'Unit Price': 'Unit Price',
            'items': 'items',
            'Walk-in Customer': 'Walk-in Customer',
            'Today': 'Today',
            'Items with issues': 'Items with issues that need attention',
            'Not available': 'Not available in system',
            'Create Sales?': 'Create Sales?',
            'This will create sale records and deduct stock': 'This will create {count} sale record(s) and deduct stock.',
            'Yes, create sales': 'Yes, create sales',
            'Creating sales...': 'Creating sales...',
            'sale(s) created successfully': '{count} sale(s) created successfully.',
            'error(s) occurred': '{count} error(s) occurred.',
            'Failed to parse document': 'Failed to parse document',
            'Error parsing document': 'Error parsing document',
            'Failed to process upload': 'Failed to process upload',
            'Error processing upload': 'Error processing upload',
            'Invalid file type': 'Invalid file type. Allowed: CSV, Excel, PDF, DOCX, Images.',
            'File too large': 'File too large. Maximum size is 10MB.',
            'No sale records found': 'No sale records found in the document.',
            'Parsing document...': 'Parsing document...',
            'Upload History': 'Upload History',
            // Module validation messages
            'Enter medicine name first': 'Enter medicine name first (e.g. "Amoxicillin 500mg capsules")',
            'Medicine name is required': 'Medicine name is required',
            'Medicine updated successfully': 'Medicine updated successfully',
            'Medicine added successfully': 'Medicine added successfully',
            'Are you sure you want to delete this medicine?': 'Are you sure you want to delete this medicine?',
            'Medicine deleted successfully': 'Medicine deleted successfully',
            'At least one item is required': 'At least one item is required',
            'Please fill all required fields in each item row': 'Please fill all required fields in each item row',
            'Please add at least one valid item': 'Please add at least one valid item',
            'Please enter a supplier name': 'Please enter a supplier name',
            'Purchase created successfully': 'Purchase created successfully',
            'Failed to create purchase': 'Failed to create purchase',
            'Failed to load purchase': 'Failed to load purchase',
            'Enter valid quantity': 'Enter valid quantity',
            'Delete this prescription? This cannot be undone': 'Delete this prescription? This cannot be undone',
            'Prescription deleted': 'Prescription deleted',
            'Please add at least one medicine': 'Please add at least one medicine',
            'Prescription updated successfully': 'Prescription updated successfully',
            'Prescription created successfully': 'Prescription created successfully',
            'Dispense this prescription? Stock will be deducted': 'Dispense this prescription? Stock will be deducted',
            'Prescription dispensed successfully': 'Prescription dispensed successfully',
            'Cancel this prescription': 'Cancel this prescription?',
            'Prescription cancelled': 'Prescription cancelled',
            'Please select a medicine': 'Please select a medicine',
            'Please select a batch': 'Please select a batch',
            'Please select source branch': 'Please select source branch',
            'Please select destination branch': 'Please select destination branch',
            'Source and destination branches must be different': 'Source and destination branches must be different',
            'Please enter a valid quantity': 'Please enter a valid quantity',
            'Quantity exceeds available stock': 'Quantity exceeds available stock ({qty})!',
            'Stock transfer submitted successfully': 'Stock transfer submitted successfully',
            'Approve this stock transfer?': 'Approve this stock transfer?',
            'Stock transfer approved': 'Stock transfer approved',
            'Reject this stock transfer?': 'Reject this stock transfer?',
            'Stock transfer rejected': 'Stock transfer rejected',
            'Please enter physical quantity': 'Please enter physical quantity',
            'Please enter a reason for the adjustment': 'Please enter a reason for the adjustment',
            'Stock adjustment submitted successfully': 'Stock adjustment submitted successfully',
            'Approve this stock adjustment?': 'Approve this stock adjustment?',
            'Stock adjustment approved': 'Stock adjustment approved',
            'Reject this stock adjustment?': 'Reject this stock adjustment?',
            'Stock adjustment rejected': 'Stock adjustment rejected',
            'Expense not found': 'Expense not found',
            'Enter valid amount and date': 'Enter valid amount and date',
            'Delete this expense?': 'Delete this expense?',
            // CRUD module messages
            'Customer not found': 'Customer not found',
            'Customer name is required': 'Customer name is required',
            'Customer updated successfully': 'Customer updated successfully',
            'Customer added successfully': 'Customer added successfully',
            'Delete this customer? This action cannot be undone': 'Delete this customer? This action cannot be undone',
            'Customer deleted successfully': 'Customer deleted successfully',
            'Update Customer': 'Update Customer',
            'Total Purchases': 'Total Purchases',
            'Total Spent': 'Total Spent',
            'Supplier name is required': 'Supplier name is required',
            'Supplier added successfully': 'Supplier added successfully',
            'Category name is required': 'Category name is required',
            'Category updated successfully': 'Category updated successfully',
            'Category added successfully': 'Category added successfully',
            'Delete this category?': 'Delete this category?',
            'Category deleted successfully': 'Category deleted successfully',
            'Manufacturer name is required': 'Manufacturer name is required',
            'Manufacturer updated successfully': 'Manufacturer updated successfully',
            'Manufacturer added successfully': 'Manufacturer added successfully',
            'Delete this manufacturer?': 'Delete this manufacturer?',
            'Manufacturer deleted successfully': 'Manufacturer deleted successfully',
            'Branch name is required': 'Branch name is required',
            'Branch updated successfully': 'Branch updated successfully',
            'Branch added successfully': 'Branch added successfully',
            'Delete this branch?': 'Delete this branch?',
            'Branch deleted successfully': 'Branch deleted successfully',
            'Please select a sale invoice': 'Please select a sale invoice',
            'Please select at least one item to return': 'Please select at least one item to return',
            'Return processed successfully': 'Return processed successfully',
            // Users
            'Add User': 'Add User',
        },
        sw: {
            // Sidebar
            'Dashboard': 'Dashibodi',
            'Medicines': 'Dawa',
            'Inventory': 'Hifadhi',
            'Sales': 'Mauzo',
            'Purchases': 'Ununuzi',
            'Suppliers': 'Wauzaji',
            'Reports': 'Ripoti',
            'Profit & Loss': 'Faida na Hasara',
            'Expenses': 'Gharama',
            'Expiry Monitor': 'Ufuatiliaji wa Muda',
            'Prescriptions': 'Vidokezo',
            'Users & Roles': 'Watumiaji na Majukumu',
            'Permissions': 'Ruhusa',
            'Activities': 'Shughuli',
            'Settings': 'Mipangilio',
            'Backup & Restore': 'Hifadhi na Urejeshaji',
            'Logout': 'Ondoka',
            // Page headers
            'Overview of your pharmacy operations': 'Muhtasari wa shughuli za duka lako la dawa',
            'Manage your medicine inventory': 'Simamia hifadhi yako ya dawa',
            'Real-time stock tracking': 'Ufuatiliaji wa hisa kwa wakati halisi',
            'Manage sales transactions': 'Simamia shughuli za mauzo',
            'Track purchase orders': 'Fuatilia amri za ununuzi',
            'Manage supplier relationships': 'Simamia uhusiano na wauzaji',
            'Analytics and insights': 'Uchambuzi na maarifa',
            'Revenue, costs and net profit': 'Mapato, gharama na faida halisi',
            'Track operating expenses': 'Fuatilia gharama za uendeshaji',
            'Monitor and manage expiring stock': 'Fuatilia na simamia hisa zinazoisha muda',
            'Database backup management': 'Usimamizi wa hifadhi ya data',
            'Process and dispense prescriptions': 'Chakatisha na peleka vidokezo',
            'Manage users and their roles': 'Simamia watumiaji na majukumu yao',
            'Manage module access per role': 'Simamia upatikanaji wa moduli kwa kila jukumu',
            'View all system activities': 'Tazama shughuli zote za mfumo',
            'Configure system settings': 'Sadirisha mipangilio ya mfumo',
            // Common
            'Loading...': 'Inapakia...',
            'No data found': 'Hakuna data',
            'Failed to load': 'Imeshindikana kupakia',
            'Success': 'Imefanikiwa',
            'Error': 'Hitilafu',
            'Warning': 'Onyo',
            'Cancel': 'Ghairi',
            'Save': 'Hifadhi',
            'Delete': 'Futa',
            'Edit': 'Hariri',
            'View': 'Tazama',
            'Search': 'Tafuta',
            'Filter': 'Chuja',
            'Refresh': 'Sasisha',
            'Print': 'Chapisha',
            'Export': 'Hamisha',
            'Close': 'Funga',
            'Confirm': 'Thibitisha',
            'Yes': 'Ndiyo',
            'No': 'Hapana',
            'OK': 'Sawa',
            'Apply': 'Tumia',
            'Generate': 'Tengeneza',
            'Submit': 'Wasilisha',
            'Processing...': 'Inachakatisha...',
            'Are you sure?': 'Una uhakika?',
            // Sales
            'Sales Dashboard': 'Dashibodi ya Mauzo',
            'Create Sale': 'Fanya Mauzo',
            'Period': 'Kipindi',
            'Today': 'Leo',
            'This Week': 'Wiki Hii',
            'This Month': 'Mwezi Huu',
            'Last Month': 'Mwezi Ulipita',
            '3 Months': 'Miezi 3',
            '5 Months': 'Miezi 5',
            '6 Months': 'Miezi 6',
            'This Year': 'Mwaka Huu',
            '5 Years': 'Miaka 5',
            'Custom Range': 'Kipindi Maalum',
            'Export CSV': 'Hamisha CSV',
            'Transactions': 'Shughuli',
            'Revenue': 'Mapato',
            'COGS': 'Gharama ya Bidhaa',
            'Net Profit': 'Faida Halisi',
            'Avg Sale': 'Wastani wa Mauzo',
            'Discounts': 'Punguzo',
            'Gross Profit': 'Faida Ghafi',
            'Margin': 'Margini',
            'Generate Report': 'Tengeneza Ripoti',
            'Sales Records': 'Rekodi za Mauzo',
            'Invoice #': 'Anuani #',
            'Date': 'Tarehe',
            'Customer': 'Mteja',
            'Items': 'Bidhaa',
            'Subtotal': 'Jumla Ndogo',
            'Discount': 'Punguzo',
            'Total': 'Jumla',
            'Actions': 'Vitendo',
            'Create New Sale': 'Fanya Mauzo Mapya',
            'Customer Name': 'Jina la Mteja',
            'Sale Date': 'Tarehe ya Mauzo',
            'Search Medicine': 'Tafuta Dawa',
            'Quantity': 'Idadi',
            'Type medicine name to search...': 'Andika jina la dawa kutafuta...',
            'Sale Items': 'Bidhaa za Mauzo',
            'Payment Method': 'Njia ya Malipo',
            'Cash': 'Fedha',
            'Mobile Money': 'Pesa ya Simu',
            'Bank Transfer': 'Uhamisho wa Benki',
            'Card': 'Kadi',
            'Credit': 'Mkopo',
            'Amount Paid': 'Kiasi Kilicholipwa',
            'Change': 'Ziada',
            'Amount Due': 'Kiasi Kinachodaiwa',
            'Notes': 'Vidokezo',
            'Complete Sale': 'Kamilisha Mauzo',
            // Purchases
            'New Purchase': 'Ununuzi Mpya',
            'Supplier Name': 'Jina la Muuzaji',
            'Purchase Date': 'Tarehe ya Ununuzi',
            'Purchase Items': 'Bidhaa za Ununuzi',
            'Create Purchase': 'Fanya Ununuzi',
            'Batch No': 'Namba ya Kundi',
            'Expiry Date': 'Tarehe ya Muda',
            'Buy Price': 'Bei ya Kununua',
            'Sell Price': 'Bei ya Kuuza',
            'Add Item': 'Ongeza Bidhaa',
            'Remove': 'Ondoa',
            // Medicines
            'Add Medicine': 'Ongeza Dawa',
            'Medicine Name': 'Jina la Dawa',
            'Generic Name': 'Jina la Jumla',
            'Brand': 'Chapa',
            'Category': 'Aina',
            'Form': 'Fomu',
            'Unit': 'Kitengo',
            'Strength': 'Ugumu',
            'Default Purchase Price': 'Bei ya Kununua',
            'Default Selling Price': 'Bei ya Kuuza',
            'Barcode': 'Nambari ya Msimbo',
            'Save Medicine': 'Hifadhi Dawa',
            // Reports
            'Report Type': 'Aina ya Ripoti',
            'Purchases Report': 'Ripoti ya Ununuzi',
            'Inventory Report': 'Ripoti ya Hifadhi',
            'Expiry Report': 'Ripoti ya Muda',
            // P&L
            'Profit Margin': 'Margini ya Faida',
            'Discounts Given': 'Punguzo Zilizotolewa',
            'Monthly Revenue': 'Mapato ya Kila Mwezi',
            'Profit & Loss Trend': 'Mwenendo wa Faida na Hasara',
            // Users
            'Add User': 'Ongeza Mtumiaji',
            'Full Name': 'Jina Kamili',
            'Email': 'Barua Pepe',
            'Password': 'Nenosiri',
            'Role': 'Jukumu',
            'Staff': 'Wafanyakazi',
            'Admin': 'Msimamizi',
            'Active': 'Hai',
            'Toggle Active': 'Badilisha Hali',
            // Suppliers
            'Add Supplier': 'Ongeza Muuzaji',
            'Company Name': 'Jina la Kampuni',
            'Contact Person': 'Mtu wa Mawasiliano',
            'Phone': 'Simu',
            'Address': 'Anwani',
            'Save Supplier': 'Hifadhi Muuzaji',
            // Login
            'Pharmacy Management': 'Usimamizi wa Duka la Dawa',
            'Secure access to your pharmacy dashboard': 'Upatikanaji salama kwa dashibodi yako',
            'Sign In': 'Ingia',
            'Notifications': 'Arifa',
            'Mark all read': 'Weka zote imesomwa',
            // Branches
            'Branches': 'Matawi',
            'Add Branch': 'Ongeza Tawi',
            'Branch Name': 'Jina la Tawi',
            'Branch Code': 'Msimbo wa Tawi',
            'Location': 'Eneo',
            'Phone Number': 'Nambari ya Simu',
            'Save Branch': 'Hifadhi Tawi',
            // Categories
            'Categories': 'Aina',
            'Add Category': 'Ongeza Aina',
            'Category Name': 'Jina la Aina',
            'Description': 'Maelezo',
            'Save Category': 'Hifadhi Aina',
            // Manufacturers
            'Manufacturers': 'Watengenezaji',
            'Add Manufacturer': 'Ongeza Mtengenezaji',
            'Manufacturer Name': 'Jina la Mtengenezaji',
            'Country': 'Nchi',
            'Save Manufacturer': 'Hifadhi Mtengenezaji',
            // Customers
            'Customers': 'Wateja',
            'Add Customer': 'Ongeza Mteja',
            'Customer Name': 'Jina la Mteja',
            'Email': 'Barua Pepe',
            'Save Customer': 'Hifadhi Mteja',
            // Stock Adjustments
            'Stock Adjustments': 'Marekebisho ya Hisa',
            'New Adjustment': 'Rekebisho Jipya',
            'Adjustment Type': 'Aina ya Rekebisho',
            'Reason': 'Sababu',
            'Adjust': 'Rekebisha',
            // Stock Transfers
            'Stock Transfers': 'Uhamishaji wa Hisa',
            'New Transfer': 'Uhamishaji Mpya',
            'From Branch': 'Kutoka Tawi',
            'To Branch': 'Kwenda Tawi',
            'Transfer Items': 'Bidhaa za Kuhamisha',
            'Transfer Stock': 'Hamisha Hisa',
            'In Transit': 'Kwenye Usafirishaji',
            'Received': 'Imepokelewa',
            // Returns
            'Returns': 'Rudisha',
            'New Return': 'Rudisha Mpya',
            'Return Reason': 'Sababu ya Kurudisha',
            'Process Return': 'Chakatisha Rudisha',
            'Returned': 'Imerudishwa',
            'Pending': 'Inasubiri',
            // Disposals
            'Disposals': 'Utupaji',
            'New Disposal': 'Utupaji Mpya',
            'Disposal Reason': 'Sababu ya Utupaji',
            'Authority': 'Mamlaka',
            'Dispose': 'Tupa',
            'Approved': 'Imeidhinishwa',
            'Disposed': 'Imetupwa',
            'TMDA Compliance': 'Kufuata TMDA',
            // Upload Sales
            'Upload Sales': 'Pakia Mauzo',
            'Upload Sales Document': 'Pakia Hati ya Mauzo',
            'Drag & drop your file here': 'Buruta na kuachilia faili yako hapa',
            'or click to browse': 'au bonyeza kuvinjari',
            'Supported formats: CSV, Excel, PDF, DOCX, PNG, JPG': 'Miundo inayotumika: CSV, Excel, PDF, DOCX, PNG, JPG',
            'Choose File': 'Chagua Faili',
            'Parse Document': 'Chambua Hati',
            'Confirm & Create Sales': 'Thibitisha na Unda Mauzo',
            'Cancel': 'Ghairi',
            'Back': 'Rudi',
            'Total Records': 'Jumla ya Rekodi',
            'Valid Records': 'Rekodi Sahihi',
            'Issues Found': 'Matatizo Yaliyopatikana',
            'Found records in file': 'Imepatikana rekodi {count} za mauzo katika faili {file}. Kagua chini na uthibitishe kuunda mauzo.',
            'Has Issues': 'Kuna Matatizo',
            'Valid': 'Sahihi',
            'OK': 'Sawa',
            'Low Stock': 'Hifadhi Ndogo',
            'Out of Stock': 'Hifadhi Imeisha',
            'Not Found': 'Haijapatikana',
            'Unit Price': 'Bei ya Kitengo',
            'items': 'bidhaa',
            'Walk-in Customer': 'Mteja wa Kutembelea',
            'Today': 'Leo',
            'Items with issues': 'Bidhaa zenye matatizo zinazohitaji ufumbuzi',
            'Not available': 'Haipatikani kwenye mfumo',
            'Create Sales?': 'Unda Mauzo?',
            'This will create sale records and deduct stock': 'Hii itaunda rekodi {count} za mauzo na kupunguza hisa.',
            'Yes, create sales': 'Ndiyo, unda mauzo',
            'Creating sales...': 'Inaunda mauzo...',
            'sale(s) created successfully': 'Mauzo {count} yameundwa kwa mafanikio.',
            'error(s) occurred': 'Hitilafu {count} zimetokea.',
            'Failed to parse document': 'Imeshindikana kuchambua hati',
            'Error parsing document': 'Hitilafu ya kuchambua hati',
            'Failed to process upload': 'Imeshindikana kuchakata upakiaji',
            'Error processing upload': 'Hitilafu ya kuchakata upakiaji',
            'Invalid file type': 'Aina ya faili si sahihi. Inaruhusiwa: CSV, Excel, PDF, DOCX, Picha.',
            'File too large': 'Faili ni kubwa sana. Ukubwa wa juu ni 10MB.',
            'No sale records found': 'Hakuna rekodi za mauzo zilizopatikana kwenye hati.',
            'Parsing document...': 'Inachambua hati...',
            'Upload History': 'Historia ya Upakiaji',
            // Module validation messages
            'Enter medicine name first': 'Weka jina la dawa kwanza (mf. "Amoxicillin 500mg capsules")',
            'Medicine name is required': 'Jina la dawa linahitajika',
            'Medicine updated successfully': 'Dawa imesasishwa kwa mafanikio',
            'Medicine added successfully': 'Dawa imeongezwa kwa mafanikio',
            'Are you sure you want to delete this medicine?': 'Una uhakika unataka kufuta dawa hii?',
            'Medicine deleted successfully': 'Dawa imefutwa kwa mafanikio',
            'At least one item is required': 'Angalau bidhaa moja inahitajika',
            'Please fill all required fields in each item row': 'Tafadhali jaza sehemu zote zinazohitajika kwenye kila safu ya bidhaa',
            'Please add at least one valid item': 'Tafadhali ongeza angalau bidhaa moja sahihi',
            'Please enter a supplier name': 'Tafadhali weka jina la muuzaji',
            'Purchase created successfully': 'Ununuzi umeundwa kwa mafanikio',
            'Failed to create purchase': 'Imeshindikana kuunda ununuzi',
            'Failed to load purchase': 'Imeshindikana kupakia ununuzi',
            'Enter valid quantity': 'Weka kiasi sahihi',
            'Delete this prescription? This cannot be undone': 'Futa dawa hii? Hii haiwezi kutenduliwa',
            'Prescription deleted': 'Dawa imefutwa',
            'Please add at least one medicine': 'Tafadhali ongeza angalau dawa moja',
            'Prescription updated successfully': 'Dawa imesasishwa kwa mafanikio',
            'Prescription created successfully': 'Dawa imeundwa kwa mafanikio',
            'Dispense this prescription? Stock will be deducted': 'Toa dawa hii? Hisa itapunguzwa',
            'Prescription dispensed successfully': 'Dawa imetolewa kwa mafanikio',
            'Cancel this prescription': 'Ghairi dawa hii?',
            'Prescription cancelled': 'Dawa imeghairiwa',
            'Please select a medicine': 'Tafadhali chagua dawa',
            'Please select a batch': 'Tafadhali chagua kundi',
            'Please select source branch': 'Tafadhali chagua tawi la chanzo',
            'Please select destination branch': 'Tafadhali chagua tawi la lengo',
            'Source and destination branches must be different': 'Matawi ya chanzo na lengo lazima yawe tofauti',
            'Please enter a valid quantity': 'Tafadhali weka kiasi sahihi',
            'Quantity exceeds available stock': 'Kiasi kimezidi hisa iliyopo ({qty})!',
            'Stock transfer submitted successfully': 'Uhamishaji wa hisa umewasilishwa kwa mafanikio',
            'Approve this stock transfer?': 'Idhinisha uhamishaji wa hisa hii?',
            'Stock transfer approved': 'Uhamishaji wa hisa umeidhinishwa',
            'Reject this stock transfer?': 'Kataa uhamishaji wa hisa hii?',
            'Stock transfer rejected': 'Uhamishaji wa hisa umekataliwa',
            'Please enter physical quantity': 'Tafadhali weka kiasi halisi',
            'Please enter a reason for the adjustment': 'Tafadhali weka sababu ya rekebisho',
            'Stock adjustment submitted successfully': 'Rekebisho la hisa limewasilishwa kwa mafanikio',
            'Approve this stock adjustment?': 'Idhinisha rekebisho la hisa hili?',
            'Stock adjustment approved': 'Rekebisho la hisa limeidhinishwa',
            'Reject this stock adjustment?': 'Kataa rekebisho la hisa hili?',
            'Stock adjustment rejected': 'Rekebisho la hisa limekataliwa',
            'Expense not found': 'Gharama haijapatikana',
            'Enter valid amount and date': 'Weka kiasi na tarehe sahihi',
            'Delete this expense?': 'Futa gharama hii?',
            // CRUD module messages
            'Customer not found': 'Mteja haijapatikana',
            'Customer name is required': 'Jina la mteja linahitajika',
            'Customer updated successfully': 'Mteja amesasishwa kwa mafanikio',
            'Customer added successfully': 'Mteja ameongezwa kwa mafanikio',
            'Delete this customer? This action cannot be undone': 'Futa mteja hii? Kitendo hiki hakiwezi kutenduliwa',
            'Customer deleted successfully': 'Mteja amefutwa kwa mafanikio',
            'Update Customer': 'Sasisha Mteja',
            'Total Purchases': 'Jumla ya Ununuzi',
            'Total Spent': 'Jumla ya Matumizi',
            'Supplier name is required': 'Jina la muuzaji linahitajika',
            'Supplier added successfully': 'Muuzaji ameongezwa kwa mafanikio',
            'Category name is required': 'Jina la aina linahitajika',
            'Category updated successfully': 'Aina imesasishwa kwa mafanikio',
            'Category added successfully': 'Aina imeongezwa kwa mafanikio',
            'Delete this category?': 'Futa aina hii?',
            'Category deleted successfully': 'Aina imefutwa kwa mafanikio',
            'Manufacturer name is required': 'Jina la mtengenezaji linahitajika',
            'Manufacturer updated successfully': 'Mtengenezaji amesasishwa kwa mafanikio',
            'Manufacturer added successfully': 'Mtengenezaji ameongezwa kwa mafanikio',
            'Delete this manufacturer?': 'Futa mtengenezaji hii?',
            'Manufacturer deleted successfully': 'Mtengenezaji amefutwa kwa mafanikio',
            'Branch name is required': 'Jina la tawi linahitajika',
            'Branch updated successfully': 'Tawi limesasishwa kwa mafanikio',
            'Branch added successfully': 'Tawi limeongezwa kwa mafanikio',
            'Delete this branch?': 'Futa tawi hili?',
            'Branch deleted successfully': 'Tawi limefutwa kwa mafanikio',
            'Please select a sale invoice': 'Tafadhali chagua anuani ya mauzo',
            'Please select at least one item to return': 'Tafadhali chagua angalau bidhaa moja ya kurudisha',
            'Return processed successfully': 'Rudisha imeshindikanywa kwa mafanikio',
        }
    }
};

window.t = function(key) {
    var lang = window.I18N.lang || 'en';
    var val = window.I18N.translations[lang] && window.I18N.translations[lang][key];
    if (val !== undefined) return val;
    var enVal = window.I18N.translations.en && window.I18N.translations.en[key];
    if (enVal !== undefined) return enVal;
    return key;
};

window.applyTranslations = function() {
    document.querySelectorAll('[data-i18n]').forEach(function(el) {
        var key = el.getAttribute('data-i18n');
        var translated = window.t(key);
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
            if (el.hasAttribute('placeholder')) {
                el.setAttribute('placeholder', translated);
            } else {
                el.value = translated;
            }
        } else {
            el.textContent = translated;
        }
    });
    var langBtn = document.getElementById('langToggle');
    if (langBtn) {
        langBtn.textContent = window.I18N.lang === 'sw' ? 'SW' : 'EN';
    }
};

window.setLanguage = function(lang) {
    if (lang !== 'en' && lang !== 'sw') return;
    window.I18N.lang = lang;
    localStorage.setItem('pharmacy_lang', lang);
    document.documentElement.lang = lang;
    window.applyTranslations();
    var active = document.querySelector('.menu-item.active');
    var page = active?.dataset?.page;
    if (page && typeof navigateTo === 'function') {
        navigateTo(page);
    }
};

window.toggleLanguage = function() {
    var next = window.I18N.lang === 'en' ? 'sw' : 'en';
    window.setLanguage(next);
};

console.log('Language module loaded');
